#pragma config(Motor,  port1,           leftWheel2,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightWheel1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftWheel35,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightWheel4,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftWheel4,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightWheel35,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftWheel1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightWheel2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setLeftWheelSpeed (int power) {
	motor[leftWheel1]  = power;
	motor[leftWheel2]  = power;
	motor[leftWheel35] = power;
	motor[leftWheel4]  = power;
}

void setRightWheelSpeed (int power) {
	motor[rightWheel1] = power;
	motor[rightWheel2] = power;
	motor[rightWheel35] = power;
	motor[rightWheel4] = power;
}

void lift(int power) {
	motor[leftLift] = power;
	motor[rightLift] = power;
}

void drivebase (int left, int right, int deadbands) {
	setLeftWheelSpeed(abs(left)<deadbands?0:left);
	setRightWheelSpeed(abs(right)<deadbands?0:right);
}

task main() {
	bool liftStay = false;
	while(true) {
		drivebase(vexRT(Ch3), vexRT(Ch2), 10);

		if(vexRT(Btn5U)) {
			lift(127);
			liftStay = false;
		} else if(vexRT(Btn5D)) {
			lift(-127);
			liftStay = false;
		} else if(liftStay)
			lift(50);
		else
			lift(0);

		if(vexRT(Btn8D)) {
			liftStay = true;
			while(vexRT(Btn8D)) { delay(5); }
		}

		if(vexRT(Btn8R)) {
			liftStay = false;
			while(vexRT(Btn8R)) { delay(5); }
		}
	}
}
